### ISSUE TITLE
Can't capture webcam pixel when switch to P3D, everything turns black

### ISSUE THREAD

**Issue by fairwelljack** [processing/processing-video#207]
Hi, I encountered this in Processing video. I was following an old tutorial about 2018 step by step. The instructor had not encountered the same issue. Everything works fine on their end. 
Everthing works fine in  2D, size(800,600); while drawing rectangles using webcam pixels to fill the color

<img width="1255" alt="Cam Capture Pixel issue 01" src="https://user-images.githubusercontent.com/49920094/193700488-cd69bc19-232f-43d8-b121-97f6f2b3d109.png">

when use  size(800,600,P3D), to draw boxes,  everything turns black, looks like it cannot catch the correct pixel[] in P3D.
<img width="1261" alt="Cam Capture Pixel issue 02" src="https://user-images.githubusercontent.com/49920094/193700560-961a15d9-6283-443b-ad7e-594e5a4da974.png">

here is the code

```
import processing.video.*;

Capture cam;

void setup(){
  background(255);
  size(800,600,P3D);
  cam = new Capture(this);
  cam.start();
}

void draw(){
  cam.loadPixels();
  int pixelSize = 50; 
  for (int y = 0; y < cam.height; y += pixelSize){
    for( int x = 0; x < cam.width; x += pixelSize){
       int camPixelPos = y * cam.width + x;
       color pixelCol = cam.pixels[camPixelPos];
       fill(pixelCol);
       
       pushMatrix();
       translate(x,y,0);
       box(pixelSize);
       popMatrix();
       
       //rect(x,y,pixelSize,pixelSize);
    }
  }
}

void captureEvent(Capture c){
  c.read();
}

```

**Comment by fairwelljack** [comment]
here's some screenshot to explain this bug. I only changed to P3D in size. When it changes to P3D, it only returns -16777216 in the console when i print pixelCol by using .pixel[] 
<img width="1157" alt="capture pixel issue 01" src="https://user-images.githubusercontent.com/49920094/193758103-acb5abc5-daf1-4a2c-9abe-5d4c3e300ae6.png">
<img width="1158" alt="capture pixel issue 02" src="https://user-images.githubusercontent.com/49920094/193758107-df60316e-2cc6-4b80-874e-c88db53b6467.png">

**Comment by ajavamind** [comment]
Not fixed with video library 2.2.2

**Comment by cacheflowe** [comment]
I just tested and can also confirm the bug on Windows 11 with the latest Processing & Processing Video lib

**Comment by jaegonlee** [comment]
try to add this in draw(). 
`image(cam,0,0,0,0);`

I tested video library in P2D, P3D mode, there are some problems with getting pixels.(and found workaround)

1. can't get pixel

```
color c = cam.get(x,y); 
fill(c);
rect(0,0,10,10); // just black only
```

add image()
```
color c = cam.get(x,y);
fill(c);
rect(0,0,10,10); 
image(cam,0,0,0,0);
```

I guess problem is in Capture.java(and Movie.java)
```
  public synchronized void read() {
    if (firstFrame) {
      super.init(sourceWidth, sourceHeight, RGB, 1);
      firstFrame = false;
    }
    if (useBufferSink) {
      if (bufferSink == null) {
        Object cache = parent.g.getCache(Capture.this); // can't get cache(texture) until call image() or texture()
        if (cache != null) {
          setBufferSink(cache);
          getSinkMethods();
```

2. slow frame rate when get pixels and display image.
```
cam.loadPixels();
...
image(cam,0,0); // very slow frame rate
```
add updatePixels()
```
cam.loadPixels();
cam.updatePixels();  
...
image(cam,0,0); // ok
```


Processing 4.1.1 / Video library 2.2.2 / MacBook Pro m1

**Comment by jaegonlee** [comment]
I found the ways to fix it.
In Capture.java(and Movie.java), replace
`Object cache = parent.g.getCache(Capture.this);`

to
```
import processing.opengl.PGraphicsOpenGL;
...
Object cache = ((PGraphicsOpenGL)(parent.g)).getTexture(Capture.this);
```
or
```
Object cache = null;
try {
  Method m = parent.g.getClass().getMethod("getTexture", new Class[] { PImage.class });
  cache = m.invoke(parent.g, new Object[] { Capture.this });
}
catch (Exception e) {
  e.printStackTrace();
}
```

**Comment by ajavamind** [comment]
jaegonlee, I noticed I still get a black screen when I use void captureEvent(Capture camera) {} instead of camera.available() in a main loop with your work around suggestion: image(camera,0,0,0,0);

void captureEvent(Capture camera) {
  image(camera, 0, 0, 0, 0);  // workaround for cache
  camera.read();
  camera.loadPixels();
  camImage[nextIndex] = camera.get();
  camIndex = nextIndex;
  nextIndex++;
  nextIndex = nextIndex & 1; // alternating 2 buffers
}


Jan 27, 2023 12:11:05 PM com.sun.jna.Native$1 uncaughtException
WARNING: JNA: Callback org.freedesktop.gstreamer.elements.AppSink$2@91cbb07 threw the following exception
java.lang.IllegalStateException: Native object has been disposed
	at org.freedesktop.gstreamer.glib.NativeObject.getRawPointer(NativeObject.java:119)
	at org.freedesktop.gstreamer.glib.Natives.getRawPointer(Natives.java:178)
	at org.freedesktop.gstreamer.lowlevel.GTypeMapper$2.toNative(GTypeMapper.java:73)
	at com.sun.jna.Function.convertArgument(Function.java:521)
	at com.sun.jna.Function.invoke(Function.java:345)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at jdk.proxy1/jdk.proxy1.$Proxy26.gst_buffer_unmap(Unknown Source)
	at org.freedesktop.gstreamer.Buffer.unmap(Buffer.java:121)
	at processing.video.Capture$NewSampleListener.newSample(Unknown Source)
	at org.freedesktop.gstreamer.elements.AppSink$2.callback(AppSink.java:232)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616)

**Comment by Asmatzaile** [comment]
Related to #203
