### ISSUE TITLE
importing existing gst library in library folder produce Error

### ISSUE THREAD

**Issue by artqcid** [processing/processing-video#222]
I put the gst1-java-core-1.4.0 on the Buildpath and now following error occurs:

```
Seems like you are trying to use GStreamer native libraries older than 1.20, which are not supported.
java.lang.UnsatisfiedLinkError: Could not load library: gstreamer
	at org.freedesktop.gstreamer.lowlevel.GstNative.load(GstNative.java:56)
	at org.freedesktop.gstreamer.lowlevel.GstNative.load(GstNative.java:46)
	at org.freedesktop.gstreamer.lowlevel.GstAPI.<clinit>(GstAPI.java:37)
	at org.freedesktop.gstreamer.Gst.getVersion(Gst.java:144)
	at org.freedesktop.gstreamer.Gst.init(Gst.java:473)
	at org.freedesktop.gstreamer.Gst.init(Gst.java:453)
```

Should not the 1.2 Version included in the download ZIP?

**Comment by artqcid** [comment]
wrong download sorry
