### ISSUE TITLE
gstreamer support on arm64 , please

### ISSUE THREAD

**Issue by aldobranti** [processing/processing-video#86]
java.lang.UnsatisfiedLinkError: Error looking up function 'gst_date_get_type': /usr/lib/aarch64-linux-gnu/libgstreamer-1.0.so.0.803.0: undefined symbol: gst_date_get_type
	at com.sun.jna.Function.<init>(Function.java:212)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:541)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:518)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:504)
	at com.sun.jna.Library$Handler.invoke(Library.java:220)
	at com.sun.proxy.$Proxy2.gst_date_get_type(Unknown Source)
	at org.gstreamer.glib.GDate.<clinit>(GDate.java:40)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.gstreamer.Gst.getField(Gst.java:447)
	at org.gstreamer.Gst.registerClass(Gst.java:460)

I would so like to export apps to an Arm based media player and have them run from boot up

slightly less significant , minimal code follows

`import processing.video.*;
Movie my_movie;

void setup(){
  size(500,500);
  my_movie = new Movie(this, "torotoro.m4v");  
  my_movie.loop();
}

void draw() {
  image( my_movie, 0,0);
}
`

**Comment by aldobranti** [comment]
#69 doesn't fix this, above message is muted but screen remains blank. comment by @davideriboli re further gstreamer0.10 packages not available as per #71

**Comment by codeanticode** [comment]
There are no plans to support arm64 at the moment, but the [GLVideo library](https://github.com/gohai/processing-glvideo) for the RPi may be an alternative.
